### ISSUE TITLE
chat never shows up

### ISSUE THREAD

**Issue by miqueet** [fishuke/better-chat#2]
![image](https://user-images.githubusercontent.com/5346303/231215607-02d0289c-74b1-4823-ba01-8ee3876325e2.png)
on the dashboard the chat never shows up. I love the idea of this project, there needs to be a better way to view twitch chat.

**Comment by fishuke** [comment]
It's been a while since i developed this project. I can try to rewrite it, but i don't have free time. Thanks for your feedback.

**Comment by fishuke** [comment]
Did you try to change credentinals and run it on your own machine?

**Comment by miqueet** [comment]
@fishuke initially i just used the github page with the hosted application. But when trying to run it locally I run into some errors.


```
root@DESKTOP-0FMV421:/home/mike/better-chat# npm run start:dev
npm run start:dev

> better-chat@0.0.0 start:dev
> ng serve --port 4200

⠋ Generating browser application bundles...(node:1464) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
⠙ Generating browser application bundles (phase: building)...node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/mike/better-chat/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mike/better-chat/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/mike/better-chat/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/mike/better-chat/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/mike/better-chat/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/mike/better-chat/node_modules/loader-runner/lib/LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (/home/mike/better-chat/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:48:13)
    at processResource (/home/mike/better-chat/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/home/mike/better-chat/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/home/mike/better-chat/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/mike/better-chat/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/mike/better-chat/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/mike/better-chat/node_modules/webpack/lib/Compilation.js:739:10)
    at /home/mike/better-chat/node_modules/webpack/lib/Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.9.0
root@DESKTOP-0FMV421:/home/mike/better-chat#
```

**Comment by fishuke** [comment]
this is a problem with node 19 try to use older version...
